import {
  Sword,
  Shield,
  Zap,
  Crown,
  Flame,
  Mountain,
  Star,
  Heart,
  Target,
  Gamepad2,
  Skull,
  Trophy,
  Swords,
  Eye,
  Users,
  Wind,
  Snowflake,
  Sun,
  Moon,
  Compass,
  Gem,
} from "lucide-react";

const GAMING_CHARACTERS = [
  {
    id: 1,
    name: "Kratos",
    title: "God of War",
    game: "God of War Series",
    icon: Sword,
    color: "from-red-600 to-orange-500",
    bgGlow: "bg-red-500/10",
    borderGlow: "border-red-500/30",
    description:
      "The Ghost of Sparta - A tale of rage, revenge, and redemption",
  },
  {
    id: 2,
    name: "Master Chief",
    title: "Spartan-117",
    game: "Halo Series",
    icon: Shield,
    color: "from-green-600 to-blue-500",
    bgGlow: "bg-green-500/10",
    borderGlow: "border-green-500/30",
    description: "Humanity's greatest defender against the Covenant",
  },
  {
    id: 3,
    name: "Geralt",
    title: "The White Wolf",
    game: "The Witcher Series",
    icon: Swords,
    color: "from-gray-400 to-amber-400",
    bgGlow: "bg-amber-500/10",
    borderGlow: "border-amber-500/30",
    description: "Monster hunter with a code of honor",
  },
  {
    id: 4,
    name: "Link",
    title: "Hero of Hyrule",
    game: "The Legend of Zelda",
    icon: Shield,
    color: "from-green-500 to-emerald-400",
    bgGlow: "bg-emerald-500/10",
    borderGlow: "border-emerald-500/30",
    description: "The legendary hero destined to save Hyrule",
  },
  {
    id: 5,
    name: "Solid Snake",
    title: "Legendary Soldier",
    game: "Metal Gear Series",
    icon: Target,
    color: "from-gray-600 to-blue-600",
    bgGlow: "bg-blue-500/10",
    borderGlow: "border-blue-500/30",
    description: "Tactical espionage operative extraordinaire",
  },
  {
    id: 6,
    name: "Samus Aran",
    title: "Intergalactic Bounty Hunter",
    game: "Metroid Series",
    icon: Zap,
    color: "from-orange-600 to-red-500",
    bgGlow: "bg-orange-500/10",
    borderGlow: "border-orange-500/30",
    description: "The galaxy's most feared bounty hunter",
  },
  {
    id: 7,
    name: "Dante",
    title: "Devil Hunter",
    game: "Devil May Cry Series",
    icon: Flame,
    color: "from-red-600 to-purple-600",
    bgGlow: "bg-red-500/10",
    borderGlow: "border-red-500/30",
    description: "Half-demon with a flair for style",
  },
  {
    id: 8,
    name: "Lara Croft",
    title: "Tomb Raider",
    game: "Tomb Raider Series",
    icon: Compass,
    color: "from-amber-600 to-orange-500",
    bgGlow: "bg-amber-500/10",
    borderGlow: "border-amber-500/30",
    description: "Adventurous archaeologist and explorer",
  },
  {
    id: 9,
    name: "Arthur Morgan",
    title: "Outlaw",
    game: "Red Dead Redemption 2",
    icon: Star,
    color: "from-amber-700 to-red-600",
    bgGlow: "bg-amber-500/10",
    borderGlow: "border-amber-500/30",
    description: "A gunslinger's tale in the dying Wild West",
  },
  {
    id: 10,
    name: "Ezio Auditore",
    title: "Master Assassin",
    game: "Assassin's Creed Series",
    icon: Eye,
    color: "from-red-700 to-gray-600",
    bgGlow: "bg-red-500/10",
    borderGlow: "border-red-500/30",
    description: "Renaissance assassin fighting for freedom",
  },
  {
    id: 11,
    name: "Gordon Freeman",
    title: "Theoretical Physicist",
    game: "Half-Life Series",
    icon: Zap,
    color: "from-orange-600 to-yellow-500",
    bgGlow: "bg-orange-500/10",
    borderGlow: "border-orange-500/30",
    description: "Scientist turned resistance leader",
  },
  {
    id: 12,
    name: "Aloy",
    title: "Machine Hunter",
    game: "Horizon Series",
    icon: Target,
    color: "from-cyan-500 to-blue-600",
    bgGlow: "bg-cyan-500/10",
    borderGlow: "border-cyan-500/30",
    description: "Hunter in a world dominated by machines",
  },
  {
    id: 13,
    name: "Shepard",
    title: "Commander",
    game: "Mass Effect Series",
    icon: Star,
    color: "from-blue-600 to-purple-600",
    bgGlow: "bg-blue-500/10",
    borderGlow: "border-blue-500/30",
    description: "Galaxy's last hope against ancient threats",
  },
  {
    id: 14,
    name: "Doom Slayer",
    title: "Hell Walker",
    game: "DOOM Series",
    icon: Skull,
    color: "from-green-600 to-red-600",
    bgGlow: "bg-green-500/10",
    borderGlow: "border-green-500/30",
    description: "Hell's worst nightmare",
  },
  {
    id: 15,
    name: "Sub-Zero",
    title: "Grandmaster",
    game: "Mortal Kombat Series",
    icon: Snowflake,
    color: "from-cyan-500 to-blue-700",
    bgGlow: "bg-cyan-500/10",
    borderGlow: "border-cyan-500/30",
    description: "Cryomancer ninja with ice-cold precision",
  },
  {
    id: 16,
    name: "Ryu",
    title: "World Warrior",
    game: "Street Fighter Series",
    icon: Flame,
    color: "from-red-600 to-orange-500",
    bgGlow: "bg-red-500/10",
    borderGlow: "border-red-500/30",
    description: "Eternal warrior seeking true strength",
  },
  {
    id: 17,
    name: "Leon Kennedy",
    title: "Special Agent",
    game: "Resident Evil Series",
    icon: Shield,
    color: "from-blue-600 to-gray-600",
    bgGlow: "bg-blue-500/10",
    borderGlow: "border-blue-500/30",
    description: "Zombie apocalypse survivor and government agent",
  },
  {
    id: 18,
    name: "Raiden",
    title: "God of Thunder",
    game: "Mortal Kombat Series",
    icon: Zap,
    color: "from-blue-400 to-white",
    bgGlow: "bg-blue-500/10",
    borderGlow: "border-blue-500/30",
    description: "Elder God protector of Earthrealm",
  },
  {
    id: 19,
    name: "Jill Valentine",
    title: "S.T.A.R.S. Member",
    game: "Resident Evil Series",
    icon: Target,
    color: "from-blue-600 to-purple-600",
    bgGlow: "bg-blue-500/10",
    borderGlow: "border-blue-500/30",
    description: "Elite operative fighting bioterrorism",
  },
  {
    id: 20,
    name: "Cloud Strife",
    title: "Ex-SOLDIER",
    game: "Final Fantasy VII",
    icon: Sword,
    color: "from-yellow-500 to-purple-600",
    bgGlow: "bg-yellow-500/10",
    borderGlow: "border-yellow-500/30",
    description: "Mercenary with a mysterious past",
  },
  {
    id: 21,
    name: "Marcus Fenix",
    title: "COG Soldier",
    game: "Gears of War Series",
    icon: Target,
    color: "from-gray-600 to-red-600",
    bgGlow: "bg-gray-500/10",
    borderGlow: "border-gray-500/30",
    description: "Hardened soldier fighting the Locust Horde",
  },
  {
    id: 22,
    name: "Nathan Drake",
    title: "Treasure Hunter",
    game: "Uncharted Series",
    icon: Compass,
    color: "from-amber-600 to-brown-600",
    bgGlow: "bg-amber-500/10",
    borderGlow: "border-amber-500/30",
    description: "Adventurous fortune hunter",
  },
  {
    id: 23,
    name: "Ellie",
    title: "Survivor",
    game: "The Last of Us Series",
    icon: Heart,
    color: "from-green-600 to-amber-600",
    bgGlow: "bg-green-500/10",
    borderGlow: "border-green-500/30",
    description: "Immune survivor in a post-apocalyptic world",
  },
  {
    id: 24,
    name: "Bayonetta",
    title: "Umbra Witch",
    game: "Bayonetta Series",
    icon: Moon,
    color: "from-purple-600 to-pink-600",
    bgGlow: "bg-purple-500/10",
    borderGlow: "border-purple-500/30",
    description: "Stylish witch with supernatural powers",
  },
];

export default GAMING_CHARACTERS;
