const gameNames = [
  "Cyberpunk 2077",
  "Elden Ring",
  "God of War: Ragnarok",
  "The Witcher 3: Wild Hunt",
  "Red Dead Redemption 2",
  "Grand Theft Auto V",
  "Assassin’s Creed Valhalla",
  "Call of Duty: Modern Warfare II",
  "Call of Duty: Warzone",
  "Hogwarts Legacy",
  "Resident Evil Village",
  "Marvel’s Spider-Man Remastered",
  "Marvel’s Spider-Man: Miles Morales",
  "Hades",
  "Stray",
  "Star Wars Jedi: Survivor",
  "Star Wars Jedi: Fallen Order",
  "A Plague Tale: Requiem",
  "The Last of Us Part I",
  "The Last of Us Part II",
  "Horizon Zero Dawn",
  "Horizon Forbidden West",
  "Ghost of Tsushima",
  "Death Stranding",
  "Sekiro: Shadows Die Twice",
  "Dark Souls III",
  "Dark Souls Remastered",
  "Demon’s Souls",
  "Baldur’s Gate 3",
  "DOOM Eternal",
  "Control",
  "Alan Wake Remastered",
  "Alan Wake II",
  "Returnal",
  "Final Fantasy VII Remake",
  "Final Fantasy XVI",
  "Monster Hunter: World",
  "Monster Hunter Rise",
  "Forza Horizon 5",
  "Gran Turismo 7",
  "The Legend of Zelda: Breath of the Wild",
  "The Legend of Zelda: Tears of the Kingdom",
  "Super Mario Odyssey",
  "Metroid Dread",
  "Fire Emblem: Three Houses",
  "Persona 5 Royal",
  "Yakuza: Like a Dragon",
  "Cuphead",
];

export default gameNames;
